/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * ZENO — The Silent Bank API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Customer dashboard summary — greeting, stats, shortcuts
 */
export declare const GetCustomerSummaryResponse: zod.ZodObject<{
    greeting: zod.ZodString;
    userName: zod.ZodString;
    balance: zod.ZodNumber;
    monthlyIncome: zod.ZodNumber;
    monthlyExpenses: zod.ZodNumber;
    expectedSavings: zod.ZodNumber;
    savingsRate: zod.ZodNumber;
    spendingMonths: zod.ZodArray<zod.ZodObject<{
        month: zod.ZodString;
        amount: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        month: string;
        amount: number;
    }, {
        month: string;
        amount: number;
    }>, "many">;
    shortcuts: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        label: zod.ZodString;
        icon: zod.ZodString;
        color: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: string;
        label: string;
        icon: string;
        color: string;
    }, {
        id: string;
        label: string;
        icon: string;
        color: string;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    greeting: string;
    userName: string;
    balance: number;
    monthlyIncome: number;
    monthlyExpenses: number;
    expectedSavings: number;
    savingsRate: number;
    spendingMonths: {
        month: string;
        amount: number;
    }[];
    shortcuts: {
        id: string;
        label: string;
        icon: string;
        color: string;
    }[];
}, {
    greeting: string;
    userName: string;
    balance: number;
    monthlyIncome: number;
    monthlyExpenses: number;
    expectedSavings: number;
    savingsRate: number;
    spendingMonths: {
        month: string;
        amount: number;
    }[];
    shortcuts: {
        id: string;
        label: string;
        icon: string;
        color: string;
    }[];
}>;
/**
 * @summary Customer recent transactions
 */
export declare const getCustomerTransactionsQueryLimitDefault = 10;
export declare const GetCustomerTransactionsQueryParams: zod.ZodObject<{
    limit: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    limit: number;
}, {
    limit?: number | undefined;
}>;
export declare const GetCustomerTransactionsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    description: zod.ZodString;
    category: zod.ZodString;
    amount: zod.ZodNumber;
    type: zod.ZodEnum<["credit", "debit"]>;
    date: zod.ZodString;
    status: zod.ZodEnum<["completed", "pending", "failed"]>;
    icon: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: "completed" | "pending" | "failed";
    type: "credit" | "debit";
    date: string;
    amount: number;
    id: string;
    description: string;
    category: string;
    icon?: string | null | undefined;
}, {
    status: "completed" | "pending" | "failed";
    type: "credit" | "debit";
    date: string;
    amount: number;
    id: string;
    description: string;
    category: string;
    icon?: string | null | undefined;
}>;
export declare const GetCustomerTransactionsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    description: zod.ZodString;
    category: zod.ZodString;
    amount: zod.ZodNumber;
    type: zod.ZodEnum<["credit", "debit"]>;
    date: zod.ZodString;
    status: zod.ZodEnum<["completed", "pending", "failed"]>;
    icon: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: "completed" | "pending" | "failed";
    type: "credit" | "debit";
    date: string;
    amount: number;
    id: string;
    description: string;
    category: string;
    icon?: string | null | undefined;
}, {
    status: "completed" | "pending" | "failed";
    type: "credit" | "debit";
    date: string;
    amount: number;
    id: string;
    description: string;
    category: string;
    icon?: string | null | undefined;
}>, "many">;
/**
 * @summary AI-style proactive recommendations for the customer
 */
export declare const GetCustomerRecommendationsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodString;
    confidence: zod.ZodNumber;
    actionLabel: zod.ZodString;
    reasoning: zod.ZodString;
    type: zod.ZodEnum<["transfer", "bill", "saving", "alert"]>;
}, "strip", zod.ZodTypeAny, {
    type: "transfer" | "bill" | "saving" | "alert";
    id: string;
    description: string;
    title: string;
    confidence: number;
    actionLabel: string;
    reasoning: string;
}, {
    type: "transfer" | "bill" | "saving" | "alert";
    id: string;
    description: string;
    title: string;
    confidence: number;
    actionLabel: string;
    reasoning: string;
}>;
export declare const GetCustomerRecommendationsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodString;
    confidence: zod.ZodNumber;
    actionLabel: zod.ZodString;
    reasoning: zod.ZodString;
    type: zod.ZodEnum<["transfer", "bill", "saving", "alert"]>;
}, "strip", zod.ZodTypeAny, {
    type: "transfer" | "bill" | "saving" | "alert";
    id: string;
    description: string;
    title: string;
    confidence: number;
    actionLabel: string;
    reasoning: string;
}, {
    type: "transfer" | "bill" | "saving" | "alert";
    id: string;
    description: string;
    title: string;
    confidence: number;
    actionLabel: string;
    reasoning: string;
}>, "many">;
/**
 * @summary Admin overview metrics
 */
export declare const GetAdminMetricsResponse: zod.ZodObject<{
    totalUsers: zod.ZodNumber;
    totalRecommendations: zod.ZodNumber;
    acceptanceRate: zod.ZodNumber;
    avgTimeSaved: zod.ZodNumber;
    pendingApprovals: zod.ZodNumber;
    topScenario: zod.ZodString;
    scenarioPerformance: zod.ZodArray<zod.ZodObject<{
        name: zod.ZodString;
        rate: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        name: string;
        rate: number;
    }, {
        name: string;
        rate: number;
    }>, "many">;
    uxMetrics: zod.ZodObject<{
        stepsBeforeZeno: zod.ZodNumber;
        stepsAfterZeno: zod.ZodNumber;
        satisfactionRate: zod.ZodNumber;
        personalizationActivation: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        stepsBeforeZeno: number;
        stepsAfterZeno: number;
        satisfactionRate: number;
        personalizationActivation: number;
    }, {
        stepsBeforeZeno: number;
        stepsAfterZeno: number;
        satisfactionRate: number;
        personalizationActivation: number;
    }>;
}, "strip", zod.ZodTypeAny, {
    totalUsers: number;
    totalRecommendations: number;
    acceptanceRate: number;
    avgTimeSaved: number;
    pendingApprovals: number;
    topScenario: string;
    scenarioPerformance: {
        name: string;
        rate: number;
    }[];
    uxMetrics: {
        stepsBeforeZeno: number;
        stepsAfterZeno: number;
        satisfactionRate: number;
        personalizationActivation: number;
    };
}, {
    totalUsers: number;
    totalRecommendations: number;
    acceptanceRate: number;
    avgTimeSaved: number;
    pendingApprovals: number;
    topScenario: string;
    scenarioPerformance: {
        name: string;
        rate: number;
    }[];
    uxMetrics: {
        stepsBeforeZeno: number;
        stepsAfterZeno: number;
        satisfactionRate: number;
        personalizationActivation: number;
    };
}>;
/**
 * @summary List recommendation rules
 */
export declare const GetAdminRulesResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    description: zod.ZodString;
    priority: zod.ZodEnum<["high", "medium", "low"]>;
    enabled: zod.ZodBoolean;
    triggerCount: zod.ZodNumber;
    acceptanceRate: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: string;
    description: string;
    acceptanceRate: number;
    name: string;
    priority: "high" | "medium" | "low";
    enabled: boolean;
    triggerCount: number;
}, {
    id: string;
    description: string;
    acceptanceRate: number;
    name: string;
    priority: "high" | "medium" | "low";
    enabled: boolean;
    triggerCount: number;
}>;
export declare const GetAdminRulesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    description: zod.ZodString;
    priority: zod.ZodEnum<["high", "medium", "low"]>;
    enabled: zod.ZodBoolean;
    triggerCount: zod.ZodNumber;
    acceptanceRate: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: string;
    description: string;
    acceptanceRate: number;
    name: string;
    priority: "high" | "medium" | "low";
    enabled: boolean;
    triggerCount: number;
}, {
    id: string;
    description: string;
    acceptanceRate: number;
    name: string;
    priority: "high" | "medium" | "low";
    enabled: boolean;
    triggerCount: number;
}>, "many">;
/**
 * @summary Toggle a recommendation rule on/off
 */
export declare const ToggleAdminRuleParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const ToggleAdminRuleResponse: zod.ZodObject<{
    rule: zod.ZodObject<{
        id: zod.ZodString;
        name: zod.ZodString;
        description: zod.ZodString;
        priority: zod.ZodEnum<["high", "medium", "low"]>;
        enabled: zod.ZodBoolean;
        triggerCount: zod.ZodNumber;
        acceptanceRate: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        id: string;
        description: string;
        acceptanceRate: number;
        name: string;
        priority: "high" | "medium" | "low";
        enabled: boolean;
        triggerCount: number;
    }, {
        id: string;
        description: string;
        acceptanceRate: number;
        name: string;
        priority: "high" | "medium" | "low";
        enabled: boolean;
        triggerCount: number;
    }>;
}, "strip", zod.ZodTypeAny, {
    rule: {
        id: string;
        description: string;
        acceptanceRate: number;
        name: string;
        priority: "high" | "medium" | "low";
        enabled: boolean;
        triggerCount: number;
    };
}, {
    rule: {
        id: string;
        description: string;
        acceptanceRate: number;
        name: string;
        priority: "high" | "medium" | "low";
        enabled: boolean;
        triggerCount: number;
    };
}>;
/**
 * @summary Full analyst insights — journey, acceptance, friction
 */
export declare const GetAnalystInsightsResponse: zod.ZodObject<{
    journeyStages: zod.ZodArray<zod.ZodObject<{
        stage: zod.ZodString;
        completion: zod.ZodNumber;
        dropOff: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        stage: string;
        completion: number;
        dropOff: number;
    }, {
        stage: string;
        completion: number;
        dropOff: number;
    }>, "many">;
    topAccepted: zod.ZodArray<zod.ZodObject<{
        title: zod.ZodString;
        rate: zod.ZodNumber;
        type: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        type: string;
        title: string;
        rate: number;
    }, {
        type: string;
        title: string;
        rate: number;
    }>, "many">;
    topRejected: zod.ZodArray<zod.ZodObject<{
        title: zod.ZodString;
        rate: zod.ZodNumber;
        reason: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        title: string;
        rate: number;
        reason: string;
    }, {
        title: string;
        rate: number;
        reason: string;
    }>, "many">;
    confidenceByType: zod.ZodArray<zod.ZodObject<{
        type: zod.ZodString;
        avg: zod.ZodNumber;
        color: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        type: string;
        color: string;
        avg: number;
    }, {
        type: string;
        color: string;
        avg: number;
    }>, "many">;
    frictionPoints: zod.ZodArray<zod.ZodObject<{
        step: zod.ZodString;
        description: zod.ZodString;
        severity: zod.ZodEnum<["high", "medium", "low"]>;
        suggestion: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        description: string;
        step: string;
        severity: "high" | "medium" | "low";
        suggestion: string;
    }, {
        description: string;
        step: string;
        severity: "high" | "medium" | "low";
        suggestion: string;
    }>, "many">;
    uxSuggestions: zod.ZodArray<zod.ZodObject<{
        title: zod.ZodString;
        impact: zod.ZodEnum<["high", "medium", "low"]>;
        effort: zod.ZodEnum<["high", "medium", "low"]>;
        description: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        description: string;
        title: string;
        impact: "high" | "medium" | "low";
        effort: "high" | "medium" | "low";
    }, {
        description: string;
        title: string;
        impact: "high" | "medium" | "low";
        effort: "high" | "medium" | "low";
    }>, "many">;
    insightTable: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        recommendation: zod.ZodString;
        type: zod.ZodString;
        acceptanceRate: zod.ZodNumber;
        avgConfidence: zod.ZodNumber;
        uxNote: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        type: string;
        id: string;
        acceptanceRate: number;
        recommendation: string;
        avgConfidence: number;
        uxNote: string;
    }, {
        type: string;
        id: string;
        acceptanceRate: number;
        recommendation: string;
        avgConfidence: number;
        uxNote: string;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    journeyStages: {
        stage: string;
        completion: number;
        dropOff: number;
    }[];
    topAccepted: {
        type: string;
        title: string;
        rate: number;
    }[];
    topRejected: {
        title: string;
        rate: number;
        reason: string;
    }[];
    confidenceByType: {
        type: string;
        color: string;
        avg: number;
    }[];
    frictionPoints: {
        description: string;
        step: string;
        severity: "high" | "medium" | "low";
        suggestion: string;
    }[];
    uxSuggestions: {
        description: string;
        title: string;
        impact: "high" | "medium" | "low";
        effort: "high" | "medium" | "low";
    }[];
    insightTable: {
        type: string;
        id: string;
        acceptanceRate: number;
        recommendation: string;
        avgConfidence: number;
        uxNote: string;
    }[];
}, {
    journeyStages: {
        stage: string;
        completion: number;
        dropOff: number;
    }[];
    topAccepted: {
        type: string;
        title: string;
        rate: number;
    }[];
    topRejected: {
        title: string;
        rate: number;
        reason: string;
    }[];
    confidenceByType: {
        type: string;
        color: string;
        avg: number;
    }[];
    frictionPoints: {
        description: string;
        step: string;
        severity: "high" | "medium" | "low";
        suggestion: string;
    }[];
    uxSuggestions: {
        description: string;
        title: string;
        impact: "high" | "medium" | "low";
        effort: "high" | "medium" | "low";
    }[];
    insightTable: {
        type: string;
        id: string;
        acceptanceRate: number;
        recommendation: string;
        avgConfidence: number;
        uxNote: string;
    }[];
}>;
/**
 * @summary List all AI recommendations
 */
export declare const GetRecommendationsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    type: zod.ZodEnum<["transfer", "bill", "travel", "saving", "alert"]>;
    title: zod.ZodString;
    description: zod.ZodString;
    reasoning: zod.ZodString;
    confidence: zod.ZodNumber;
    supportingFacts: zod.ZodArray<zod.ZodObject<{
        label: zod.ZodString;
        detail: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        label: string;
        detail: string;
    }, {
        label: string;
        detail: string;
    }>, "many">;
    status: zod.ZodEnum<["pending", "accepted", "rejected"]>;
    beneficiary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    amount: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    currency: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "accepted" | "rejected";
    type: "transfer" | "bill" | "saving" | "alert" | "travel";
    id: string;
    description: string;
    title: string;
    confidence: number;
    reasoning: string;
    supportingFacts: {
        label: string;
        detail: string;
    }[];
    currency: string;
    createdAt: string;
    amount?: number | null | undefined;
    beneficiary?: string | null | undefined;
}, {
    status: "pending" | "accepted" | "rejected";
    type: "transfer" | "bill" | "saving" | "alert" | "travel";
    id: string;
    description: string;
    title: string;
    confidence: number;
    reasoning: string;
    supportingFacts: {
        label: string;
        detail: string;
    }[];
    currency: string;
    createdAt: string;
    amount?: number | null | undefined;
    beneficiary?: string | null | undefined;
}>;
export declare const GetRecommendationsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    type: zod.ZodEnum<["transfer", "bill", "travel", "saving", "alert"]>;
    title: zod.ZodString;
    description: zod.ZodString;
    reasoning: zod.ZodString;
    confidence: zod.ZodNumber;
    supportingFacts: zod.ZodArray<zod.ZodObject<{
        label: zod.ZodString;
        detail: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        label: string;
        detail: string;
    }, {
        label: string;
        detail: string;
    }>, "many">;
    status: zod.ZodEnum<["pending", "accepted", "rejected"]>;
    beneficiary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    amount: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    currency: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "accepted" | "rejected";
    type: "transfer" | "bill" | "saving" | "alert" | "travel";
    id: string;
    description: string;
    title: string;
    confidence: number;
    reasoning: string;
    supportingFacts: {
        label: string;
        detail: string;
    }[];
    currency: string;
    createdAt: string;
    amount?: number | null | undefined;
    beneficiary?: string | null | undefined;
}, {
    status: "pending" | "accepted" | "rejected";
    type: "transfer" | "bill" | "saving" | "alert" | "travel";
    id: string;
    description: string;
    title: string;
    confidence: number;
    reasoning: string;
    supportingFacts: {
        label: string;
        detail: string;
    }[];
    currency: string;
    createdAt: string;
    amount?: number | null | undefined;
    beneficiary?: string | null | undefined;
}>, "many">;
/**
 * @summary Accept a recommendation — moves it to approvals
 */
export declare const AcceptRecommendationParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const AcceptRecommendationResponse: zod.ZodObject<{
    recommendation: zod.ZodObject<{
        id: zod.ZodString;
        type: zod.ZodEnum<["transfer", "bill", "travel", "saving", "alert"]>;
        title: zod.ZodString;
        description: zod.ZodString;
        reasoning: zod.ZodString;
        confidence: zod.ZodNumber;
        supportingFacts: zod.ZodArray<zod.ZodObject<{
            label: zod.ZodString;
            detail: zod.ZodString;
        }, "strip", zod.ZodTypeAny, {
            label: string;
            detail: string;
        }, {
            label: string;
            detail: string;
        }>, "many">;
        status: zod.ZodEnum<["pending", "accepted", "rejected"]>;
        beneficiary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        amount: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        currency: zod.ZodString;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: "pending" | "accepted" | "rejected";
        type: "transfer" | "bill" | "saving" | "alert" | "travel";
        id: string;
        description: string;
        title: string;
        confidence: number;
        reasoning: string;
        supportingFacts: {
            label: string;
            detail: string;
        }[];
        currency: string;
        createdAt: string;
        amount?: number | null | undefined;
        beneficiary?: string | null | undefined;
    }, {
        status: "pending" | "accepted" | "rejected";
        type: "transfer" | "bill" | "saving" | "alert" | "travel";
        id: string;
        description: string;
        title: string;
        confidence: number;
        reasoning: string;
        supportingFacts: {
            label: string;
            detail: string;
        }[];
        currency: string;
        createdAt: string;
        amount?: number | null | undefined;
        beneficiary?: string | null | undefined;
    }>;
    approval: zod.ZodOptional<zod.ZodObject<{
        id: zod.ZodString;
        recommendationId: zod.ZodString;
        operation: zod.ZodString;
        beneficiary: zod.ZodString;
        amount: zod.ZodNumber;
        currency: zod.ZodString;
        reasoning: zod.ZodString;
        status: zod.ZodEnum<["awaiting_confirmation", "confirmed_demo", "cancelled"]>;
        acceptedAt: zod.ZodString;
        confirmedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    }, "strip", zod.ZodTypeAny, {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    }, {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    }>>;
}, "strip", zod.ZodTypeAny, {
    recommendation: {
        status: "pending" | "accepted" | "rejected";
        type: "transfer" | "bill" | "saving" | "alert" | "travel";
        id: string;
        description: string;
        title: string;
        confidence: number;
        reasoning: string;
        supportingFacts: {
            label: string;
            detail: string;
        }[];
        currency: string;
        createdAt: string;
        amount?: number | null | undefined;
        beneficiary?: string | null | undefined;
    };
    approval?: {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    } | undefined;
}, {
    recommendation: {
        status: "pending" | "accepted" | "rejected";
        type: "transfer" | "bill" | "saving" | "alert" | "travel";
        id: string;
        description: string;
        title: string;
        confidence: number;
        reasoning: string;
        supportingFacts: {
            label: string;
            detail: string;
        }[];
        currency: string;
        createdAt: string;
        amount?: number | null | undefined;
        beneficiary?: string | null | undefined;
    };
    approval?: {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    } | undefined;
}>;
/**
 * @summary Reject a recommendation
 */
export declare const RejectRecommendationParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const RejectRecommendationResponse: zod.ZodObject<{
    recommendation: zod.ZodObject<{
        id: zod.ZodString;
        type: zod.ZodEnum<["transfer", "bill", "travel", "saving", "alert"]>;
        title: zod.ZodString;
        description: zod.ZodString;
        reasoning: zod.ZodString;
        confidence: zod.ZodNumber;
        supportingFacts: zod.ZodArray<zod.ZodObject<{
            label: zod.ZodString;
            detail: zod.ZodString;
        }, "strip", zod.ZodTypeAny, {
            label: string;
            detail: string;
        }, {
            label: string;
            detail: string;
        }>, "many">;
        status: zod.ZodEnum<["pending", "accepted", "rejected"]>;
        beneficiary: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        amount: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        currency: zod.ZodString;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: "pending" | "accepted" | "rejected";
        type: "transfer" | "bill" | "saving" | "alert" | "travel";
        id: string;
        description: string;
        title: string;
        confidence: number;
        reasoning: string;
        supportingFacts: {
            label: string;
            detail: string;
        }[];
        currency: string;
        createdAt: string;
        amount?: number | null | undefined;
        beneficiary?: string | null | undefined;
    }, {
        status: "pending" | "accepted" | "rejected";
        type: "transfer" | "bill" | "saving" | "alert" | "travel";
        id: string;
        description: string;
        title: string;
        confidence: number;
        reasoning: string;
        supportingFacts: {
            label: string;
            detail: string;
        }[];
        currency: string;
        createdAt: string;
        amount?: number | null | undefined;
        beneficiary?: string | null | undefined;
    }>;
}, "strip", zod.ZodTypeAny, {
    recommendation: {
        status: "pending" | "accepted" | "rejected";
        type: "transfer" | "bill" | "saving" | "alert" | "travel";
        id: string;
        description: string;
        title: string;
        confidence: number;
        reasoning: string;
        supportingFacts: {
            label: string;
            detail: string;
        }[];
        currency: string;
        createdAt: string;
        amount?: number | null | undefined;
        beneficiary?: string | null | undefined;
    };
}, {
    recommendation: {
        status: "pending" | "accepted" | "rejected";
        type: "transfer" | "bill" | "saving" | "alert" | "travel";
        id: string;
        description: string;
        title: string;
        confidence: number;
        reasoning: string;
        supportingFacts: {
            label: string;
            detail: string;
        }[];
        currency: string;
        createdAt: string;
        amount?: number | null | undefined;
        beneficiary?: string | null | undefined;
    };
}>;
/**
 * @summary List pending and confirmed approvals
 */
export declare const GetApprovalsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    recommendationId: zod.ZodString;
    operation: zod.ZodString;
    beneficiary: zod.ZodString;
    amount: zod.ZodNumber;
    currency: zod.ZodString;
    reasoning: zod.ZodString;
    status: zod.ZodEnum<["awaiting_confirmation", "confirmed_demo", "cancelled"]>;
    acceptedAt: zod.ZodString;
    confirmedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
    amount: number;
    id: string;
    reasoning: string;
    beneficiary: string;
    currency: string;
    recommendationId: string;
    operation: string;
    acceptedAt: string;
    confirmedAt?: string | null | undefined;
}, {
    status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
    amount: number;
    id: string;
    reasoning: string;
    beneficiary: string;
    currency: string;
    recommendationId: string;
    operation: string;
    acceptedAt: string;
    confirmedAt?: string | null | undefined;
}>;
export declare const GetApprovalsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    recommendationId: zod.ZodString;
    operation: zod.ZodString;
    beneficiary: zod.ZodString;
    amount: zod.ZodNumber;
    currency: zod.ZodString;
    reasoning: zod.ZodString;
    status: zod.ZodEnum<["awaiting_confirmation", "confirmed_demo", "cancelled"]>;
    acceptedAt: zod.ZodString;
    confirmedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
    amount: number;
    id: string;
    reasoning: string;
    beneficiary: string;
    currency: string;
    recommendationId: string;
    operation: string;
    acceptedAt: string;
    confirmedAt?: string | null | undefined;
}, {
    status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
    amount: number;
    id: string;
    reasoning: string;
    beneficiary: string;
    currency: string;
    recommendationId: string;
    operation: string;
    acceptedAt: string;
    confirmedAt?: string | null | undefined;
}>, "many">;
/**
 * @summary Final confirmation — marks as confirmed_demo (no real execution)
 */
export declare const ConfirmApprovalParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const ConfirmApprovalResponse: zod.ZodObject<{
    approval: zod.ZodObject<{
        id: zod.ZodString;
        recommendationId: zod.ZodString;
        operation: zod.ZodString;
        beneficiary: zod.ZodString;
        amount: zod.ZodNumber;
        currency: zod.ZodString;
        reasoning: zod.ZodString;
        status: zod.ZodEnum<["awaiting_confirmation", "confirmed_demo", "cancelled"]>;
        acceptedAt: zod.ZodString;
        confirmedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    }, "strip", zod.ZodTypeAny, {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    }, {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    }>;
}, "strip", zod.ZodTypeAny, {
    approval: {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    };
}, {
    approval: {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    };
}>;
/**
 * @summary Cancel a pending approval
 */
export declare const CancelApprovalParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const CancelApprovalResponse: zod.ZodObject<{
    approval: zod.ZodObject<{
        id: zod.ZodString;
        recommendationId: zod.ZodString;
        operation: zod.ZodString;
        beneficiary: zod.ZodString;
        amount: zod.ZodNumber;
        currency: zod.ZodString;
        reasoning: zod.ZodString;
        status: zod.ZodEnum<["awaiting_confirmation", "confirmed_demo", "cancelled"]>;
        acceptedAt: zod.ZodString;
        confirmedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    }, "strip", zod.ZodTypeAny, {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    }, {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    }>;
}, "strip", zod.ZodTypeAny, {
    approval: {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    };
}, {
    approval: {
        status: "awaiting_confirmation" | "confirmed_demo" | "cancelled";
        amount: number;
        id: string;
        reasoning: string;
        beneficiary: string;
        currency: string;
        recommendationId: string;
        operation: string;
        acceptedAt: string;
        confirmedAt?: string | null | undefined;
    };
}>;
/**
 * @summary Get dashboard summary with balances, stats, and recent transactions
 */
export declare const GetDashboardSummaryResponse: zod.ZodObject<{
    totalBalance: zod.ZodNumber;
    monthlyIncome: zod.ZodNumber;
    monthlyExpenses: zod.ZodNumber;
    savingsRate: zod.ZodNumber;
    recentTransactions: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        accountId: zod.ZodString;
        type: zod.ZodEnum<["credit", "debit"]>;
        amount: zod.ZodNumber;
        currency: zod.ZodString;
        description: zod.ZodString;
        category: zod.ZodString;
        merchant: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        status: zod.ZodEnum<["completed", "pending", "failed"]>;
        date: zod.ZodString;
        icon: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    }, "strip", zod.ZodTypeAny, {
        status: "completed" | "pending" | "failed";
        type: "credit" | "debit";
        date: string;
        amount: number;
        id: string;
        description: string;
        category: string;
        currency: string;
        accountId: string;
        icon?: string | null | undefined;
        merchant?: string | null | undefined;
    }, {
        status: "completed" | "pending" | "failed";
        type: "credit" | "debit";
        date: string;
        amount: number;
        id: string;
        description: string;
        category: string;
        currency: string;
        accountId: string;
        icon?: string | null | undefined;
        merchant?: string | null | undefined;
    }>, "many">;
    accountsOverview: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        name: zod.ZodString;
        balance: zod.ZodNumber;
        type: zod.ZodString;
        currency: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        type: string;
        balance: number;
        id: string;
        name: string;
        currency: string;
    }, {
        type: string;
        balance: number;
        id: string;
        name: string;
        currency: string;
    }>, "many">;
    alerts: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        type: zod.ZodString;
        message: zod.ZodString;
        severity: zod.ZodEnum<["info", "warning", "success"]>;
    }, "strip", zod.ZodTypeAny, {
        message: string;
        type: string;
        id: string;
        severity: "info" | "warning" | "success";
    }, {
        message: string;
        type: string;
        id: string;
        severity: "info" | "warning" | "success";
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    monthlyIncome: number;
    monthlyExpenses: number;
    savingsRate: number;
    totalBalance: number;
    recentTransactions: {
        status: "completed" | "pending" | "failed";
        type: "credit" | "debit";
        date: string;
        amount: number;
        id: string;
        description: string;
        category: string;
        currency: string;
        accountId: string;
        icon?: string | null | undefined;
        merchant?: string | null | undefined;
    }[];
    accountsOverview: {
        type: string;
        balance: number;
        id: string;
        name: string;
        currency: string;
    }[];
    alerts: {
        message: string;
        type: string;
        id: string;
        severity: "info" | "warning" | "success";
    }[];
}, {
    monthlyIncome: number;
    monthlyExpenses: number;
    savingsRate: number;
    totalBalance: number;
    recentTransactions: {
        status: "completed" | "pending" | "failed";
        type: "credit" | "debit";
        date: string;
        amount: number;
        id: string;
        description: string;
        category: string;
        currency: string;
        accountId: string;
        icon?: string | null | undefined;
        merchant?: string | null | undefined;
    }[];
    accountsOverview: {
        type: string;
        balance: number;
        id: string;
        name: string;
        currency: string;
    }[];
    alerts: {
        message: string;
        type: string;
        id: string;
        severity: "info" | "warning" | "success";
    }[];
}>;
/**
 * @summary List all user accounts
 */
export declare const GetAccountsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    type: zod.ZodEnum<["checking", "savings", "investment"]>;
    balance: zod.ZodNumber;
    currency: zod.ZodString;
    iban: zod.ZodString;
    accountNumber: zod.ZodString;
    interestRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    isDefault: zod.ZodBoolean;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: "checking" | "savings" | "investment";
    balance: number;
    id: string;
    name: string;
    currency: string;
    createdAt: string;
    iban: string;
    accountNumber: string;
    isDefault: boolean;
    interestRate?: number | null | undefined;
}, {
    type: "checking" | "savings" | "investment";
    balance: number;
    id: string;
    name: string;
    currency: string;
    createdAt: string;
    iban: string;
    accountNumber: string;
    isDefault: boolean;
    interestRate?: number | null | undefined;
}>;
export declare const GetAccountsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    type: zod.ZodEnum<["checking", "savings", "investment"]>;
    balance: zod.ZodNumber;
    currency: zod.ZodString;
    iban: zod.ZodString;
    accountNumber: zod.ZodString;
    interestRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    isDefault: zod.ZodBoolean;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: "checking" | "savings" | "investment";
    balance: number;
    id: string;
    name: string;
    currency: string;
    createdAt: string;
    iban: string;
    accountNumber: string;
    isDefault: boolean;
    interestRate?: number | null | undefined;
}, {
    type: "checking" | "savings" | "investment";
    balance: number;
    id: string;
    name: string;
    currency: string;
    createdAt: string;
    iban: string;
    accountNumber: string;
    isDefault: boolean;
    interestRate?: number | null | undefined;
}>, "many">;
/**
 * @summary Get account by ID
 */
export declare const GetAccountParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const GetAccountResponse: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    type: zod.ZodEnum<["checking", "savings", "investment"]>;
    balance: zod.ZodNumber;
    currency: zod.ZodString;
    iban: zod.ZodString;
    accountNumber: zod.ZodString;
    interestRate: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    isDefault: zod.ZodBoolean;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: "checking" | "savings" | "investment";
    balance: number;
    id: string;
    name: string;
    currency: string;
    createdAt: string;
    iban: string;
    accountNumber: string;
    isDefault: boolean;
    interestRate?: number | null | undefined;
}, {
    type: "checking" | "savings" | "investment";
    balance: number;
    id: string;
    name: string;
    currency: string;
    createdAt: string;
    iban: string;
    accountNumber: string;
    isDefault: boolean;
    interestRate?: number | null | undefined;
}>;
/**
 * @summary List transactions with optional filtering
 */
export declare const getTransactionsQueryLimitDefault = 20;
export declare const GetTransactionsQueryParams: zod.ZodObject<{
    accountId: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodOptional<zod.ZodString>;
    limit: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    limit: number;
    category?: string | undefined;
    accountId?: string | undefined;
}, {
    limit?: number | undefined;
    category?: string | undefined;
    accountId?: string | undefined;
}>;
export declare const GetTransactionsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    accountId: zod.ZodString;
    type: zod.ZodEnum<["credit", "debit"]>;
    amount: zod.ZodNumber;
    currency: zod.ZodString;
    description: zod.ZodString;
    category: zod.ZodString;
    merchant: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["completed", "pending", "failed"]>;
    date: zod.ZodString;
    icon: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: "completed" | "pending" | "failed";
    type: "credit" | "debit";
    date: string;
    amount: number;
    id: string;
    description: string;
    category: string;
    currency: string;
    accountId: string;
    icon?: string | null | undefined;
    merchant?: string | null | undefined;
}, {
    status: "completed" | "pending" | "failed";
    type: "credit" | "debit";
    date: string;
    amount: number;
    id: string;
    description: string;
    category: string;
    currency: string;
    accountId: string;
    icon?: string | null | undefined;
    merchant?: string | null | undefined;
}>;
export declare const GetTransactionsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    accountId: zod.ZodString;
    type: zod.ZodEnum<["credit", "debit"]>;
    amount: zod.ZodNumber;
    currency: zod.ZodString;
    description: zod.ZodString;
    category: zod.ZodString;
    merchant: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["completed", "pending", "failed"]>;
    date: zod.ZodString;
    icon: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: "completed" | "pending" | "failed";
    type: "credit" | "debit";
    date: string;
    amount: number;
    id: string;
    description: string;
    category: string;
    currency: string;
    accountId: string;
    icon?: string | null | undefined;
    merchant?: string | null | undefined;
}, {
    status: "completed" | "pending" | "failed";
    type: "credit" | "debit";
    date: string;
    amount: number;
    id: string;
    description: string;
    category: string;
    currency: string;
    accountId: string;
    icon?: string | null | undefined;
    merchant?: string | null | undefined;
}>, "many">;
/**
 * @summary Get transaction by ID
 */
export declare const GetTransactionParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const GetTransactionResponse: zod.ZodObject<{
    id: zod.ZodString;
    accountId: zod.ZodString;
    type: zod.ZodEnum<["credit", "debit"]>;
    amount: zod.ZodNumber;
    currency: zod.ZodString;
    description: zod.ZodString;
    category: zod.ZodString;
    merchant: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodEnum<["completed", "pending", "failed"]>;
    date: zod.ZodString;
    icon: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: "completed" | "pending" | "failed";
    type: "credit" | "debit";
    date: string;
    amount: number;
    id: string;
    description: string;
    category: string;
    currency: string;
    accountId: string;
    icon?: string | null | undefined;
    merchant?: string | null | undefined;
}, {
    status: "completed" | "pending" | "failed";
    type: "credit" | "debit";
    date: string;
    amount: number;
    id: string;
    description: string;
    category: string;
    currency: string;
    accountId: string;
    icon?: string | null | undefined;
    merchant?: string | null | undefined;
}>;
/**
 * @summary List all user cards
 */
export declare const GetCardsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    accountId: zod.ZodString;
    type: zod.ZodEnum<["visa", "mastercard"]>;
    cardNumber: zod.ZodString;
    cardHolder: zod.ZodString;
    expiryDate: zod.ZodString;
    cvv: zod.ZodString;
    isVirtual: zod.ZodBoolean;
    isFrozen: zod.ZodBoolean;
    spendingLimit: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    currentSpend: zod.ZodNumber;
    color: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: "visa" | "mastercard";
    id: string;
    color: string;
    createdAt: string;
    accountId: string;
    cardNumber: string;
    cardHolder: string;
    expiryDate: string;
    cvv: string;
    isVirtual: boolean;
    isFrozen: boolean;
    currentSpend: number;
    spendingLimit?: number | null | undefined;
}, {
    type: "visa" | "mastercard";
    id: string;
    color: string;
    createdAt: string;
    accountId: string;
    cardNumber: string;
    cardHolder: string;
    expiryDate: string;
    cvv: string;
    isVirtual: boolean;
    isFrozen: boolean;
    currentSpend: number;
    spendingLimit?: number | null | undefined;
}>;
export declare const GetCardsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    accountId: zod.ZodString;
    type: zod.ZodEnum<["visa", "mastercard"]>;
    cardNumber: zod.ZodString;
    cardHolder: zod.ZodString;
    expiryDate: zod.ZodString;
    cvv: zod.ZodString;
    isVirtual: zod.ZodBoolean;
    isFrozen: zod.ZodBoolean;
    spendingLimit: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    currentSpend: zod.ZodNumber;
    color: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: "visa" | "mastercard";
    id: string;
    color: string;
    createdAt: string;
    accountId: string;
    cardNumber: string;
    cardHolder: string;
    expiryDate: string;
    cvv: string;
    isVirtual: boolean;
    isFrozen: boolean;
    currentSpend: number;
    spendingLimit?: number | null | undefined;
}, {
    type: "visa" | "mastercard";
    id: string;
    color: string;
    createdAt: string;
    accountId: string;
    cardNumber: string;
    cardHolder: string;
    expiryDate: string;
    cvv: string;
    isVirtual: boolean;
    isFrozen: boolean;
    currentSpend: number;
    spendingLimit?: number | null | undefined;
}>, "many">;
/**
 * @summary Get card by ID
 */
export declare const GetCardParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const GetCardResponse: zod.ZodObject<{
    id: zod.ZodString;
    accountId: zod.ZodString;
    type: zod.ZodEnum<["visa", "mastercard"]>;
    cardNumber: zod.ZodString;
    cardHolder: zod.ZodString;
    expiryDate: zod.ZodString;
    cvv: zod.ZodString;
    isVirtual: zod.ZodBoolean;
    isFrozen: zod.ZodBoolean;
    spendingLimit: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    currentSpend: zod.ZodNumber;
    color: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: "visa" | "mastercard";
    id: string;
    color: string;
    createdAt: string;
    accountId: string;
    cardNumber: string;
    cardHolder: string;
    expiryDate: string;
    cvv: string;
    isVirtual: boolean;
    isFrozen: boolean;
    currentSpend: number;
    spendingLimit?: number | null | undefined;
}, {
    type: "visa" | "mastercard";
    id: string;
    color: string;
    createdAt: string;
    accountId: string;
    cardNumber: string;
    cardHolder: string;
    expiryDate: string;
    cvv: string;
    isVirtual: boolean;
    isFrozen: boolean;
    currentSpend: number;
    spendingLimit?: number | null | undefined;
}>;
/**
 * @summary Get spending breakdown by category
 */
export declare const GetSpendingAnalyticsResponse: zod.ZodObject<{
    totalSpent: zod.ZodNumber;
    period: zod.ZodString;
    categories: zod.ZodArray<zod.ZodObject<{
        category: zod.ZodString;
        amount: zod.ZodNumber;
        percentage: zod.ZodNumber;
        color: zod.ZodString;
        transactionCount: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        amount: number;
        color: string;
        category: string;
        percentage: number;
        transactionCount: number;
    }, {
        amount: number;
        color: string;
        category: string;
        percentage: number;
        transactionCount: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    totalSpent: number;
    period: string;
    categories: {
        amount: number;
        color: string;
        category: string;
        percentage: number;
        transactionCount: number;
    }[];
}, {
    totalSpent: number;
    period: string;
    categories: {
        amount: number;
        color: string;
        category: string;
        percentage: number;
        transactionCount: number;
    }[];
}>;
/**
 * @summary Get monthly income vs expenses for the past 6 months
 */
export declare const GetMonthlyAnalyticsResponseItem: zod.ZodObject<{
    month: zod.ZodString;
    income: zod.ZodNumber;
    expenses: zod.ZodNumber;
    savings: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    month: string;
    savings: number;
    income: number;
    expenses: number;
}, {
    month: string;
    savings: number;
    income: number;
    expenses: number;
}>;
export declare const GetMonthlyAnalyticsResponse: zod.ZodArray<zod.ZodObject<{
    month: zod.ZodString;
    income: zod.ZodNumber;
    expenses: zod.ZodNumber;
    savings: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    month: string;
    savings: number;
    income: number;
    expenses: number;
}, {
    month: string;
    savings: number;
    income: number;
    expenses: number;
}>, "many">;
/**
 * @summary List user notifications
 */
export declare const GetNotificationsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    type: zod.ZodEnum<["transaction", "security", "offer", "system"]>;
    title: zod.ZodString;
    message: zod.ZodString;
    isRead: zod.ZodBoolean;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    message: string;
    type: "transaction" | "security" | "offer" | "system";
    id: string;
    title: string;
    createdAt: string;
    isRead: boolean;
}, {
    message: string;
    type: "transaction" | "security" | "offer" | "system";
    id: string;
    title: string;
    createdAt: string;
    isRead: boolean;
}>;
export declare const GetNotificationsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    type: zod.ZodEnum<["transaction", "security", "offer", "system"]>;
    title: zod.ZodString;
    message: zod.ZodString;
    isRead: zod.ZodBoolean;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    message: string;
    type: "transaction" | "security" | "offer" | "system";
    id: string;
    title: string;
    createdAt: string;
    isRead: boolean;
}, {
    message: string;
    type: "transaction" | "security" | "offer" | "system";
    id: string;
    title: string;
    createdAt: string;
    isRead: boolean;
}>, "many">;
/**
 * @summary Get user profile
 */
export declare const GetProfileResponse: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    email: zod.ZodString;
    phone: zod.ZodString;
    avatar: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    tier: zod.ZodEnum<["standard", "premium", "elite"]>;
    joinedAt: zod.ZodString;
    lastLogin: zod.ZodString;
    preferredLanguage: zod.ZodString;
    twoFactorEnabled: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    id: string;
    name: string;
    email: string;
    phone: string;
    tier: "standard" | "premium" | "elite";
    joinedAt: string;
    lastLogin: string;
    preferredLanguage: string;
    twoFactorEnabled: boolean;
    avatar?: string | null | undefined;
}, {
    id: string;
    name: string;
    email: string;
    phone: string;
    tier: "standard" | "premium" | "elite";
    joinedAt: string;
    lastLogin: string;
    preferredLanguage: string;
    twoFactorEnabled: boolean;
    avatar?: string | null | undefined;
}>;
//# sourceMappingURL=api.d.ts.map